### ISSUE TITLE
Alt balloon does not update its position on external changes

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-image#106]
![apr-24-2017 19-02-59](https://cloud.githubusercontent.com/assets/1057056/25349905/a5840b68-2923-11e7-9c64-9c14c3d0e065.gif)

This may be fixed together with: https://github.com/ckeditor/ckeditor5-image/issues/96

A follow-up of https://github.com/ckeditor/ckeditor5-ui/issues/198.

**Comment by oleq** [comment]
> This may be fixed together with: #96

I don't think so, although it will certainly make the code shorter. What we need is a `render` event listener, while `CB` listens to `scroll` and `resize`. My first thought was to make `CB` render-aware, but now I think it's not such a good idea because sometimes we want to get rid of the balloon when there's a `render`, like [this](https://github.com/ckeditor/ckeditor5-image/blob/master/src/image/ui/imageballoonpanelview.js#L40-L46)

```js
// Hide the balloon if no image is currently selected.
editor.listenTo( editingView, 'render', () => {
	const selectedElement = editingView.selection.getSelectedElement();

	if ( !selectedElement || !isImageWidget( selectedElement ) ) {
		this.detach();
	}
}, { priority: 'low' } );
```

**Comment by Reinmar** [comment]
Removed milestone because it can wait until the UI library refactoring (https://github.com/ckeditor/ckeditor5-ui/issues/225) which will enable https://github.com/ckeditor/ckeditor5-image/issues/96.

**Comment by Reinmar** [comment]
Unfortunately we need to come up with a hack before we'll fix https://github.com/ckeditor/ckeditor5-ui/issues/225.
