### ISSUE TITLE
Double image toolbar when ContextualToolbar plugin is loaded

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-image#110]
![may-09-2017 11-19-34](https://cloud.githubusercontent.com/assets/1057056/25844024/7dc44124-34a9-11e7-9342-e4b9734cc4e0.gif)

**Comment by oleq** [comment]
It's probably the same as https://github.com/ckeditor/ckeditor5-ui/issues/222#issuecomment-300104362, isn't it?

**Comment by oskarwrobel** [comment]
It is similar. Image can check if `CT` plugin is loaded and if it is, then uses `beforeShow` event to block `CT`of being displayed when the selection contains only image element.

**Comment by oleq** [comment]
Yes. At this stage it makes sense. But soon we'll struggle with these problems:
1. We may support some global commands when the image is selected, like the Link. How would users link such content if there's no toolbar? Keep in mind that tables will come with similar toolbar and the problem gets quite serious because you'd expect there's some way to bold table content, etc.
2. What if the image is the only item in the editable and the user wants to undo but there's no global toolbar?

So I guess we'd need to integrate this image toolbar with the contextual editor toolbar, i.e. the image–specific buttons will be displayed at the end of such toolbar.

**Comment by Reinmar** [comment]
> What if the image is the only item in the editable and the user wants to undo but there's no global toolbar?

First of all, there are keystrokes. Second of all – the undo buttons should not be place in the  contextual toolbar at all. It makes no sense. Contextual toolbar should be used for actions which are contextual.

> We may support some global commands when the image is selected, like the Link. How would users link such content if there's no toolbar? Keep in mind that tables will come with similar toolbar and the problem gets quite serious because you'd expect there's some way to bold table content, etc.

The image toolbar needs to be correctly configured. It should feature the link button in such a case.
