### ISSUE TITLE
ImageStyleCommand cannot switch between two non-default styles

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-image#132]
I wanted to define two styles – left or right aligned. No default, class-less style. So I changed the configuration to:

```js
		editor.config.define( 'image.styles', [
			// This option is equal to situation when no style is applied.
			{ name: 'imageStyleFull', title: 'Bar', icon: fullSizeIcon,  value: 'bar', className: 'image-style-bar' },

			// This represents side image.
			{ name: 'imageStyleSide', title: t( 'Side image' ), icon: sideIcon, value: 'side', className: 'image-style-side' }
		] );
```

This broke the feature completely. If you load a sample which contains a side image, you can click the "Bar" style but the only thing which happens is that the image loses the class. It can't get any class after that.

--- 

**Update:**

If you have three styles: `left, null (default), right` then switching between `left/right <-> null` works fine. But `left <-> right` does not.

**Comment by Reinmar** [comment]
My issue description is wrong. They do not work at all when trying to switch between two non-null styles. This is high prior issue.

**Comment by Reinmar** [comment]
cc @m-kr who experienced it

**Comment by oleq** [comment]
The issue was funny. In this [line](https://github.com/ckeditor/ckeditor5-image/blob/master/src/imagestyle/converters.js#L33), if `handleRemoval` returned `true`, `handleAddition` was never called and that's why the view de-synchronized with the model.

Tests didn't catch it because they tested `editor.getData()` output, which, if I got it correctly, does everything from scratch – the model to data conversion is `addAttribute`–driven, not `changeAttribute`, which clearly failed.

**Comment by szymonkups** [comment]
I've added model->view checks to these tests inside PR closing this issue.
