### ISSUE TITLE
Image should re-render view on load

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-image#142]
[edited]
Sometimes the source of the image element is loaded async and this causes layout change. We need to reposition UI attached to the content then.

E.g. Image element is rendered in the DOM after pressing `Start external changes` but image is heavy and we need to wait a couple of seconds to see the source of the image. The image is loaded but UI is in the old position because its its update was not triggered:
![sep-25-2017 11-40-19](https://user-images.githubusercontent.com/1057056/30802340-79546a74-a1e6-11e7-9868-ef99882a7d18.gif)

**Comment by oleq** [comment]
It looks more like a bug in ckeditor5-link. Since there's no selection enclosing the image after the external insertion, the link balloon should simply hide and no image UI should show up.

The sample does not show what happened to the selection after the insertion, though. If it's still in the link, the link balloon should simply be re-positioned.

**Comment by oskarwrobel** [comment]
Link is still in the document after image insert.

**Comment by oskarwrobel** [comment]
Gif has been replaced.

**Comment by oskarwrobel** [comment]
We need to get image from DOM, listen to its `load` event and call `viewDoc.render()` or just fire `viewDoc#render` event. Question is when we should start to listen to this event. During model -> view conversion?

**Comment by oleq** [comment]
cc @szymonkups

**Comment by oskarwrobel** [comment]
I added MT for this ticker https://github.com/ckeditor/ckeditor5-image/tree/t/142/tests/manual/tickets/142.
