### ISSUE TITLE
Split ImageResize to ImageResizeEditing and ImageResizeUI

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5-image#304]
## Is this a bug report or feature request?

Task

## 📋 Steps to reproduce

Currently there's only a `ImageResize` plugin. It should be split as other plugins, into Editing and UI.

**Comment by jodator** [comment]
To not create too many issues: The code coverage for imageresize.js is below 100% - a missing test case for overwriting converter.

And since I was looking at the test few things that I don't like there:
1. The docs for `generateResizeTest()` could be updated and moved from funciton body to normal `// hidden jsdoc` format, ie:
    ```js
    // Desc...
    //
    // @param {Object} options
    // @param {String} options.resizerPosition
    funciton generateResizerTest( options )
    ```
2. I like the idea of function that generates tests that returns a function rather then creating internal `it()` call :+1: 
3. I'm not sure if I like the `optionsmodelRegExp` - it' too complex to read in a test case I think that would be better to rewrite this, ie:
    * the `<paragraph>foo</paragraph>` bloats test - I'd remove it completly or make it transparent to the tests methods
    * the amount of `width=([\d]{2}(?:\.[\d]{1,2}))` is also too much - couldnt we create some expectansion for this?
        ```js
        generateResizeTest( {
            // .. other options
            expect: {
                width: `45.6%` // or even a regex for value if some computational quirks
            }
        } )
        ```
    * ~The `options.expectedWidth` might be `options.expect.domWidth` (the DOM part is missing in the variable)~ I've get to the methods internals - I don't see point in testing model RegExp when we can simply check model values and only regexp test them instead of a whole model contents. It is really hard to read :(

**Comment by Reinmar** [comment]
The entire part of ImageResize belongs to ImageResizeEditing (no other UI parts right now) so for now let's keep a single class.
