### ISSUE TITLE
Error when caption needs to be brought back on undo/redo

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-image#58]
1. Open http://localhost:8125/ckeditor5-image/tests/manual/caption.html.
2. Type few letters in the second image's caption.
3. Press undo.
4. Move selection out of the caption (so it disappears).
5. Press redo.

Error is thrown. I think that it's caused by the fact that undo's changes try to insert content into the caption which isn't in the view at that moment. Any idea how to deal with this?

**Comment by Reinmar** [comment]
Perhaps a solution would be to listen on conversion's `insert` event and if insert happens inside model's `<caption>`, then adding the `<figcaption>` in the view too. Am I right?

This means that perhaps the standard converter from `<caption>` to `<figcaption>` can be removed because the above one will handle all the situations.

**Comment by Reinmar** [comment]
Alternatively – we should never remove the caption from the view. But this means that we'll have to implement mechanisms to not render it if we want to be puristic or style it with `display:none` as a KISS solution.

For me all solutions are OK, but the one with removing the caption from the view if it shouldn't be visible seems to be the most "correct".

**Comment by scofalik** [comment]
Looking at the error, I am almost sure the reason you've written is correct. As you already figured out, there are multiple ways to tackle this issue.

> we'll have to implement mechanisms to not render it if we want to be puristic

I understand that you would like some elements from view not to be rendered in DOM? I am against. Seems magical and brings complications in `Renderer`. For me, view is "the DOM but without quirks" and we use it only because we have to deal with browsers. I'd rather stick with the idea that what's in view is in DOM.

> Perhaps a solution would be to listen on conversion's insert event and if insert happens inside model's <caption>, then adding the <figcaption> in the view too. Am I right?

Given how current solution looks like this seems like the easiest fix. I am not sure though if it should look like this. I would refrain from specifying too many "global" callbacks for efficiency and debugging reasons. (BTW. it looks like this `document.on( 'change', insertMissingCaptionElement );` could be just `insert:image` converter. It would be faster, easier to debug and implementation should be easier too - you would not have to look for the image).

> style it with `display:none`

I fear, that the problem with this solution is that if we know that if we know that we should apply/remove the style, we are also able to just insert/remove the whole element from the view. So it just doesn't solve much. Of course, now editor blows because we don't have the element. But if we go with `display:none` we will have to fix the bug that the caption doesn't show.

As for now I don't have a clear idea how to solve, but I'll think about it as it's interesting case. It's probably first time when we deal with the problem that element's conversion depends on element's children. I am not sure if we ever allowed such scenario. Maybe we should just not allow it?

I wanted to write that it would be best if it was all based on conversion mechanisms, and suggested that maybe adding/removing `<figcaption>` should be done on selection conversion. However on second thought we are dealing purely with UI/UX stuff here and I am not sure if it should be driven by conversion. OTOH I just wrote that view -> DOM should not be magical, so we need to add UI stuff to the view (heck we even introduced `UIElement`).

So I guess I am a bit torn, here are my thoughts, but I have a feeling I haven't been much helpful :P.

**Comment by scofalik** [comment]
Anyway the fix that you proposed should work so we can accept it as (temporary) solution if we won't come up with something more elegant.

**Comment by Reinmar** [comment]
> For me, view is "the DOM but without quirks" and we use it only because we have to deal with browsers

Not only for that because the main goal of implementing a virtual DOM is to let you perform many operations without touching the DOM if not necessary. But I agree with the first part.

> I'd rather stick with the idea that what's in view is in DOM.

+1.

> (BTW. it looks like this document.on( 'change', insertMissingCaptionElement ); could be just insert:image converter. It would be faster, easier to debug and implementation should be easier too - you would not have to look for the image).

This is a different story IIRC – it adds a missing caption to the model element (as a post-fixer). The current mechanism which shows a caption if empty is triggered by a selection converter IIRC.

> So I guess I am a bit torn, here are my thoughts, but I have a feeling I haven't been much helpful :P.

Well, I'm a bit torn too. Complicating the view rendering any further doesn't seem to be the cleanest solution because we agree that the view should be as close to the DOM as possible. Using inline styles is not a solution either because, as you noticed, we'd need exactly the same logic to remove that style on undo :D. Besides, I have some feeling that hiding elements in the DOM may have some impact on the selection (but maybe I'm wrong because it's quite the same case as doing other modifications and setting the selection afterwards – nothing bad happens now).

So, this leaves us with the solution that we did implement – removing the `<figcaption>` from the view when it should be hidden. Which means that we need to find a solution for the issue I reported initially. I guess the open question is how :D.

Anyway, I quite like the solution that `<figcaption>` is added as an early listener on any `insert` if the insert discovers to be inside model's `<caption>` which doesn't have corresponding `<figcaption>`. OTOH, I agree that it's yet another global listener. OTTH, why did we introduce those event namespaces if not for that exactly? :) Besides, it's all about precisely targeting the listener so it triggers only when needed. Then it's usually safe.
