### ISSUE TITLE
Integration with ContextualBalloon plugin

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-image#96]
Image plugin should use [ContextualBalloon](https://github.com/ckeditor/ckeditor5-ui/blob/master/src/contextualballoon.js) to display balloon panels like [Link plugin does](https://github.com/ckeditor/ckeditor5-link/blob/master/src/link.js#L29-L30).

**Comment by oleq** [comment]
Shouldn't it also use [`ContextualToolbar`](https://github.com/ckeditor/ckeditor5-ui/pull/188)?

**Comment by Reinmar** [comment]
I think it was meant to use CtxToolbar because toolbar changes into the alt text balloon so they were meant to be synced this way.

**Comment by oleq** [comment]
I spent some time (2 days...) working on this integration but to no avail. It turned out that 2 separate plugins, sharing the asynchronous API of `ContextualBalloon` and [reacting to `render`, which fires like a crazy](https://github.com/ckeditor/ckeditor5-image/issues/106), are a way too much to handle. 

Because of the high frequency of `render` event (+occastional changes to the focus), the `ContextualBalloon` `add|remove` promises overlap and collide producing tons of errors. To handle this, a sophisticated promise queueing system would be necessary for the `ContextualBalloon`, and that wouldn't be enough in my opinion because even if queued, some promises wouldn't make sense when their turn to resolve arrives e.g. because the previous ones managed to modify the DOM they needed.

The sheer complexity of the code made me decide to drop the attempt to straighten this out and I suppose there's no other way than to wait for https://github.com/ckeditor/ckeditor5-ui/issues/225#issuecomment-300126000.
